swagger: '2.0'
info:
  title: Kubernetes
  version: v1.17.6
paths: []
definitions:
  io.k8s.config.examples/api.apps.v1.Deployment:
    description: Deployment enables declarative updates for Pods and ReplicaSets.
    type: object
    properties:
    example: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        # Unique key of the Deployment instance
        name: deployment-example
      spec:
        # 3 Pods should exist at all times.
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              # Apply this label to pods and default
              # the Deployment label selector to this value
              app: nginx
          spec:
            containers:
            - name: nginx
              # Run this image
              image: nginx:1.14